services:
  backend:
    build:
      context: ./backend
    container_name: spotify-downloader-backend
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_URL
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: spotify-downloader-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL
    restart: unless-stopped
