services:
  - type: web
    name: backend
    env: docker
    region: oregon
    plan: free
    dockerContext: ../..
    dockerFilePath: Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
